### ISSUE TITLE
Dúvidas sobre o desafio

### ISSUE THREAD

**Issue by thiagorowof** [justapagamentos/desafio-front#1]
Gostaria de saber alguns pontos sobre esse teste!

- Qual o prazo de entrega?
- Quando sai o resultado da seleção?
- É necessário _forkar_ aqui o repositório e subir o projeto? como devemos enviar o projeto?

Tem algum contato alem do email do rai.siqueira@justa.com.vc e it@justa.com.vc ? Gostaria de conversar algumas coisas (mais dúvidas no geral) sobre a vaga!

obrigado!

**Comment by raisiqueira** [comment]
Fala, Thiago!

- Não tem prazo, mas estamos correndo com a contratação, então quanto mais rápido você cumprir o desafio, mas rápido vamos entrar em contato com você (já respondendo a segunda questão).

- Não é necessário _forkar_ o projeto, assim que cumprir o desafio, você pode me enviar um e-mail, ou enviar um e-mail para o _it@justa.com.vc_ que já marcamos uma call contigo.

**Comment by thiagorowof** [comment]
Legal,
Irei correr pra fazer e concluir no máximo amanhã.

Irei pegar essa oportunidade dando o meu melhor possível!
